// Mock data for streams
export interface Stream {
  id: string;
  title: string;
  author: string;
  thumbnail: string;
  url: string;
  category: string;
  viewers: number;
  isLive: boolean;
  duration?: string;
  description: string;
  tags: string[];
}

export const categories = [
  "All",
  "Gaming",
  "Music",
  "Tech",
  "Nature",
  "Travel",
  "Cooking",
  "Sports",
  "Art",
] as const;

export const mockStreams: Stream[] = [
  {
    id: "1",
    title: "Epic Mountain Adventure - 4K Nature Documentary",
    author: "NatureExplorer",
    thumbnail: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
    url: "https://www.youtube.com/watch?v=z9Ug-3qhrwY",
    category: "Nature",
    viewers: 12500,
    isLive: true,
    description: "Explore breathtaking mountain landscapes in stunning 4K",
    tags: ["nature", "mountains", "4k", "documentary"],
  },
  {
    id: "2",
    title: "Cyberpunk Cityscape - Night Driving",
    author: "CyberPunkGaming",
    thumbnail: "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800",
    url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    category: "Gaming",
    viewers: 8900,
    isLive: true,
    description: "Immersive cyberpunk city exploration",
    tags: ["gaming", "cyberpunk", "night", "city"],
  },
  {
    id: "3",
    title: "Peaceful Ocean Waves - Meditation Sounds",
    author: "CalmSounds",
    thumbnail: "https://images.unsplash.com/photo-1505142468610-359e7d316be0?w=800",
    url: "https://www.youtube.com/watch?v=example3",
    category: "Nature",
    viewers: 15400,
    isLive: true,
    description: "Relaxing ocean waves for meditation",
    tags: ["ocean", "meditation", "relaxing", "nature"],
  },
  {
    id: "4",
    title: "Space Station Live Stream - Earth from Orbit",
    author: "SpaceChannel",
    thumbnail: "https://images.unsplash.com/photo-1446776877081-d282a0f896e2?w=800",
    url: "https://www.youtube.com/watch?v=oXsBLbUUe3c",
    category: "Tech",
    viewers: 32100,
    isLive: true,
    description: "Live view of Earth from the International Space Station",
    tags: ["space", "earth", "live", "tech"],
  },
  {
    id: "5",
    title: "Tokyo Street Walking Tour - Shibuya District",
    author: "TokyoWalker",
    thumbnail: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800",
    url: "https://www.youtube.com/watch?v=example5",
    category: "Travel",
    viewers: 11200,
    isLive: true,
    description: "Walk through the vibrant streets of Shibuya, Tokyo",
    tags: ["tokyo", "travel", "walking", "city"],
  },
  {
    id: "6",
    title: "Neon Synthwave Highway - Retro Vibes",
    author: "SynthWaveVibes",
    thumbnail: "https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=800",
    url: "https://www.youtube.com/watch?v=example6",
    category: "Music",
    viewers: 6800,
    isLive: true,
    description: "Retro synthwave aesthetic with neon lights",
    tags: ["synthwave", "retro", "neon", "music"],
  },
  {
    id: "7",
    title: "Rainforest Canopy - Bird Watching",
    author: "WildlifeHD",
    thumbnail: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800",
    url: "https://www.youtube.com/watch?v=example7",
    category: "Nature",
    viewers: 9200,
    isLive: true,
    description: "Explore the diverse bird life in the rainforest canopy",
    tags: ["rainforest", "birds", "wildlife", "nature"],
  },
  {
    id: "8",
    title: "Virtual Reality Gameplay - Sci-Fi Adventure",
    author: "VRGamer",
    thumbnail: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800",
    url: "https://www.youtube.com/watch?v=example8",
    category: "Gaming",
    viewers: 18700,
    isLive: true,
    description: "Immersive VR sci-fi adventure gameplay",
    tags: ["vr", "gaming", "sci-fi", "adventure"],
  },
  {
    id: "9",
    title: "Sunset over Desert Dunes - Timelapse",
    author: "DesertVisions",
    thumbnail: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800",
    url: "https://www.youtube.com/watch?v=example9",
    category: "Nature",
    viewers: 14300,
    isLive: false,
    duration: "5:24",
    description: "Stunning timelapse of sunset over desert sand dunes",
    tags: ["desert", "sunset", "timelapse", "nature"],
  },
  {
    id: "10",
    title: "Jazz Club Live Performance",
    author: "JazzLive",
    thumbnail: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800",
    url: "https://www.youtube.com/watch?v=example10",
    category: "Music",
    viewers: 5600,
    isLive: true,
    description: "Live jazz performance in an intimate club setting",
    tags: ["jazz", "live", "music", "performance"],
  },
  {
    id: "lofi-1",
    title: "lofi hip hop radio — beats to relax/study to",
    author: "Lofi Girl",
    thumbnail: "https://i.ytimg.com/vi/jfKfPfyJRdk/hqdefault.jpg",
    url: "https://www.youtube.com/watch?v=jfKfPfyJRdk",
    category: "Music",
    viewers: 38000,
    isLive: true,
    description: "24/7 chill beats for studying and relaxing.",
    tags: ["lofi", "live", "radio", "study"]
  },
  {
    id: "iss-1",
    title: "ISS Live — Earth From Space (24/7)",
    author: "Space Videos",
    thumbnail: "https://i.ytimg.com/vi/xRPjKQtRXR8/hqdefault.jpg",
    url: "https://www.youtube.com/watch?v=xRPjKQtRXR8",
    category: "Tech",
    viewers: 2100,
    isLive: true,
    description: "Live high-definition views of Earth from the International Space Station.",
    tags: ["space", "earth", "iss", "live"]
  },
  {
    id: "shibuya-1",
    title: "【4K HDR】Night Walk in Tokyo — Shibuya",
    author: "VIRTUAL JAPAN",
    thumbnail: "https://i.ytimg.com/vi/0nTO4zSEpOs/hqdefault.jpg",
    url: "https://www.youtube.com/watch?v=0nTO4zSEpOs",
    category: "Travel",
    viewers: 15400,
    isLive: false,
    duration: "1:09:49",
    description: "A night walking tour through Shibuya in 4K HDR.",
    tags: ["tokyo", "shibuya", "walk", "4k"]
  },
  {
    id: "cyberpunk-1",
    title: "[4K] Late Night Drive in Night City (Cyberpunk 2077 Ambience)",
    author: "World of Ambient",
    thumbnail: "https://i.ytimg.com/vi/hHcQpjlPAGo/hqdefault.jpg",
    url: "https://www.youtube.com/watch?v=hHcQpjlPAGo",
    category: "Gaming",
    viewers: 8900,
    isLive: false,
    duration: "1:00:32",
    description: "Third-person cruise around Night City at night with ray tracing.",
    tags: ["cyberpunk", "drive", "4k", "ambience"]
  },
  {
    id: "birds-1",
    title: "Canopy Voyage: Birds in 4K — Macaws, Toucans & Quetzals",
    author: "Wildlife Relaxation",
    thumbnail: "https://i.ytimg.com/vi/PRBlkH1BqYY/hqdefault.jpg",
    url: "https://www.youtube.com/watch?v=PRBlkH1BqYY",
    category: "Nature",
    viewers: 13200,
    isLive: false,
    duration: "1:02:18",
    description: "Rainforest canopy wildlife with natural sounds in true 4K.",
    tags: ["rainforest", "birds", "4k", "nature"]
  },
  {
    id: "desert-1",
    title: "White Sands National Park — Sunset Timelapse (4K)",
    author: "Roadtrippers",
    thumbnail: "https://i.ytimg.com/vi/aWSE2YNOp7Y/hqdefault.jpg",
    url: "https://www.youtube.com/watch?v=aWSE2YNOp7Y",
    category: "Nature",
    viewers: 7400,
    isLive: false,
    duration: "3:52",
    description: "Stunning sunset over gypsum dunes at White Sands.",
    tags: ["timelapse", "desert", "sunset", "4k"]
  },
  {
    id: "vr-1",
    title: "Memoreum — Official Gameplay Trailer (VR)",
    author: "UploadVR",
    thumbnail: "https://i.ytimg.com/vi/6wNyn0MOsQw/hqdefault.jpg",
    url: "https://www.youtube.com/watch?v=6wNyn0MOsQw",
    category: "Gaming",
    viewers: 6200,
    isLive: false,
    duration: "1:27",
    description: "Sci-fi survival horror VR gameplay showcase.",
    tags: ["vr", "sci-fi", "gameplay", "trailer"]
  },
  {
    id: "jazz-1",
    title: "Olivia Dean — Live at The Jazz Cafe (Full Set)",
    author: "Olivia Dean",
    thumbnail: "https://i.ytimg.com/vi/St7G1F4mu_4/hqdefault.jpg",
    url: "https://www.youtube.com/watch?v=St7G1F4mu_4",
    category: "Music",
    viewers: 5600,
    isLive: false,
    duration: "35:24",
    description: "Soulful live performance recorded at The Jazz Cafe.",
    tags: ["jazz", "live", "soul", "concert"]
  },
  {
    id: "synth-1",
    title: "Night Drive — 12 Hours (4K 60fps)",
    author: "VISUALDON",
    thumbnail: "https://i.ytimg.com/vi/xrW4MitN2kw/hqdefault.jpg",
    url: "https://www.youtube.com/watch?v=xrW4MitN2kw",
    category: "Music",
    viewers: 6800,
    isLive: false,
    duration: "12:00:00",
    description: "Retro synthwave highway visuals for focus and vibes.",
    tags: ["synthwave", "retro", "visuals", "4k"]
  },
  {
    id: "nba-1",
    title: "Top 100 Plays of the 2023–24 NBA Season",
    author: "NBA",
    thumbnail: "https://i.ytimg.com/vi/8HLO9QC_YJU/hqdefault.jpg",
    url: "https://www.youtube.com/watch?v=8HLO9QC_YJU",
    category: "Sports",
    viewers: 231000,
    isLive: false,
    duration: "27:31",
    description: "The best dunks, dimes, blocks, and buzzer-beaters of the season.",
    tags: ["nba", "highlights", "top-100", "basketball"]
  },
  {
    id: "ramen-1",
    title: "How To Make Real Tonkotsu Ramen",
    author: "Way of Ramen",
    thumbnail: "https://i.ytimg.com/vi/uPqzY8rZLZM/hqdefault.jpg",
    url: "https://www.youtube.com/watch?v=uPqzY8rZLZM",
    category: "Cooking",
    viewers: 4200,
    isLive: false,
    duration: "15:19",
    description: "Traditional rich and creamy tonkotsu broth from scratch.",
    tags: ["ramen", "tonkotsu", "recipe", "noodles"]
  },
  {
    id: "babish-ramen",
    title: "Tonkotsu Ramen | Basics with Babish",
    author: "Babish Culinary Universe",
    thumbnail: "https://i.ytimg.com/vi/jFM_rJ5MtYk/hqdefault.jpg",
    url: "https://www.youtube.com/watch?v=jFM_rJ5MtYk",
    category: "Cooking",
    viewers: 9800,
    isLive: false,
    duration: "19:36",
    description: "Homemade tare, chashu, noodles, and broth walkthrough.",
    tags: ["ramen", "basics", "cooking", "tutorial"]
  },
  {
    id: "f1-monaco-24",
    title: "Charles Leclerc’s Pole Lap | 2024 Monaco Grand Prix",
    author: "FORMULA 1",
    thumbnail: "https://i.ytimg.com/vi/TmJFVfU1RuI/hqdefault.jpg",
    url: "https://www.youtube.com/watch?v=TmJFVfU1RuI",
    category: "Sports",
    viewers: 450000,
    isLive: false,
    duration: "1:58",
    description: "Onboard with Leclerc around the streets of Monaco.",
    tags: ["f1", "monaco", "onboard", "pole"]
  },
  {
    id: "bbb-1",
    title: "Big Buck Bunny — Full Movie (HD)",
    author: "Blender Foundation",
    thumbnail: "https://i.ytimg.com/vi/aqz-KE-bpKQ/hqdefault.jpg",
    url: "https://www.youtube.com/watch?v=aqz-KE-bpKQ",
    category: "Tech",
    viewers: 1250000,
    isLive: false,
    duration: "9:56",
    description: "Open-source animated short used for graphics demos and tests.",
    tags: ["blender", "open-source", "animation", "demo"]
  },
  {
    id: "art-portrait-1",
    title: "Realistic Portrait in 6 Hours — Oil Painting Timelapse",
    author: "Art Studio",
    thumbnail: "https://i.ytimg.com/vi/EWdR23jO1_Y/hqdefault.jpg",
    url: "https://www.youtube.com/watch?v=EWdR23jO1_Y",
    category: "Art",
    viewers: 2700,
    isLive: false,
    duration: "12:44",
    description: "Step-by-step portrait painting time-lapse in oils.",
    tags: ["art", "oil", "portrait", "timelapse"]
  },
  {
    id: "tokyo-ramen-street",
    title: "[4K] Tokyo Ramen Street — How to Go & Have Ramen",
    author: "Tokyo Travel Guide",
    thumbnail: "https://i.ytimg.com/vi/iyPsHrgezLs/hqdefault.jpg",
    url: "https://www.youtube.com/watch?v=iyPsHrgezLs",
    category: "Travel",
    viewers: 8300,
    isLive: false,
    duration: "10:21",
    description: "Guide to Tokyo Station’s famous Ramen Street.",
    tags: ["tokyo", "ramen", "travel", "guide"]
  },
  {
    id: "cyberpunk-ambient-2",
    title: "‘Above The Neon City’ — 12 Hours (4K 60fps)",
    author: "VISUALDON",
    thumbnail: "https://i.ytimg.com/vi/pwuFTsvJL34/hqdefault.jpg",
    url: "https://www.youtube.com/watch?v=pwuFTsvJL34",
    category: "Art",
    viewers: 5400,
    isLive: false,
    duration: "12:00:00",
    description: "Blade-Runner-inspired ambient skyline visuals.",
    tags: ["ambient", "neon", "visuals", "4k"]
  },
  {
    id: "rainforest-2",
    title: "Canopy Secrets — Exotic Bird Families in 4K",
    author: "Wildlife Relaxation",
    thumbnail: "https://i.ytimg.com/vi/RSsbWzPjosE/hqdefault.jpg",
    url: "https://www.youtube.com/watch?v=RSsbWzPjosE",
    category: "Nature",
    viewers: 7600,
    isLive: false,
    duration: "59:54",
    description: "Cinematic rainforest wildlife with natural soundscape.",
    tags: ["birds", "rainforest", "4k", "wildlife"]
  },
  {
    id: "jazz-2",
    title: "Jazz Night In America — Live at Brooklyn Steel (BADBADNOTGOOD)",
    author: "Jazz Night In America",
    thumbnail: "https://i.ytimg.com/vi/0L-5xvX2Z48/hqdefault.jpg",
    url: "https://www.youtube.com/watch?v=0L-5xvX2Z48",
    category: "Music",
    viewers: 22000,
    isLive: false,
    duration: "1:05:43",
    description: "Full concert performance from BADBADNOTGOOD.",
    tags: ["jazz", "live", "concert", "badbadnotgood"]
  }
];

